#!/usr/bin/env ruby
# FILE: gems/presto-cli/exe/presto
# frozen_string_literal: true

require 'bundler/setup'
lib_path = File.expand_path('../lib', __dir__)
$LOAD_PATH.unshift(lib_path) unless $LOAD_PATH.include?(lib_path)

require 'presto/cli'
require 'presto/cli/application'

Presto::CLI::Application.start(ARGV)
