source 'https://rubygems.org'

gem 'presto-core', path: '../../gems/presto-core'

group :development do
  gem 'thor', '~> 1.3'
  gem 'rake', '~> 13.0'
  gem 'rspec', '~> 3.12'
  gem 'rubocop', '~> 1.50'
end
